### ISSUE TITLE
html5css3?

### ISSUE THREAD

**Issue by quantbo** [spbooks/htmlcss2#1]
The book is titled HTML5 & CSS3 etc. Shouldn't this repo be htmlcss3, or better yet html5css3?

**Comment by simonmackie** [comment]
Hey @quantbo , sorry  for the confusion. HTMLCSS2 is our internal SKU for the book, as it is the second edition of the book. I realize that is not helpful when there are version numbers attached to the technoogy too, but hopefully that explains why it is so named.

**Comment by quantbo** [comment]
Thanks for clarifying.
